advertise-endpoint-url: ""
advertise-token: ""
lookup-endpoint-type: indexer
lookup-endpoint-url: https://cid.contact
max-bitswap-workers: 1
routing-table-type: dht
prune-threshold: 45 GB
pin-duration: 1h0m0s
log-resource-manager: false
log-retrieval-stats: false
disable-retrieval: false
cid-blacklist: []
miner-blacklist: []
miner-whitelist: []
default-miner-config:
    retrieval-timeout: 1m0s
    max-concurrent-retrievals: 1
miner-configs: {}
