apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoretrieve
  namespace: autoretrieve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoretrieve
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: autoretrieve
    spec:
      containers:
        - name: autoretrieve
          image: autoretrieve
          args:
            - --data-dir=/data
          envFrom:
            - configMapRef:
                name: autoretrieve-env
          ports:
            - name: libp2p
              containerPort: 6746
            - name: admin
              containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: libp2p
          volumeMounts:
            - name: config
              mountPath: /data/config.yaml
              subPath: config.yaml
            - name: identity
              mountPath: /data/peerkey
              subPath: peerkey
          resources:
            limits:
              memory: 32Gi
            requests:
              memory: 32Gi
      volumes:
        - name: config
          configMap:
            name: autoretrieve-config
        - name: identity
          secret:
            secretName: autoretrieve-identity
            items:
              - key: peerkey.encrypted
                path: ./peerkey
